### ISSUE TITLE
Program Written in Incorrect Language

### ISSUE THREAD

**Issue by mabotkin** [Devon-Austin-Wood-Thomas/tj-shell-scripts#1]
This program is written in an extremely high level interpreted language.  Not all systems have or support the necessary prerequisite software needed to run this program.  Consider a lower level language such as Bash instead. :)

**Comment by gengkev** [comment]
The only reason why you wouldn't have Python is that you're using Windows

**Comment by gengkev** [comment]
Also, just because shell scripting is an abomination doesn't mean it's necessarily "lower-level". Consider parsing JSON in a language such as C instead.
